apiVersion: apps/v1
kind: Deployment
metadata:
  name: intellipaat-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: intellipaat-app
  template:
    metadata:
      labels:
        app: intellipaat-app
    spec:
      containers:
      - name: intellipaat-app
        image: mohanmanav/intellipaat-app:04
        ports:
        - containerPort: 8585