apiVersion: apps/v1
kind: Deployment
metadata:
  name: intellipaat-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: intellipaat-app
  template:
    metadata:
      labels:
        app: intellipaat-app
  spec:  # This is the Pod specification (corrected indentation)
      containers:
        - name: intellipaat-app
          image: mohanmanav/intellipaat-app:03
          ports:
            - containerPort: 80 # Exposed port on the container
