apiVersion: apps/v1
kind: Deployment
metadata:
  name: intellipaat-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: intellipaat-app
  template:
    metadata:
      labels:
        app: intellipaat-app
    spec:
      containers:
      - name: intellipaat-app
        image: mohanmanav/intellipaat-app:01
        ports:
        - containerPort: 80
