apiVersion: apps/v1
kind: Deployment
metadata:
  name: intellipaat-app
  labels:
    app: intellipaat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intellipaat-app
  template:
    metadata:
      labels:
        app: intellipaat-app
    spec:
      containers:
        - name: intellipaat-app
          image: mohanmanav/intellipaat-app:04
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8585
          resources:
            limits:
              cpu: 0.2
              memory: "200Mi"
          
---
apiVersion: v1
kind: Service
metadata:
  name: intellipaat-app
  labels:
    app: intellipaat-app
spec:
  type: LoadBalancer
  selector:
    app: intellipaat-app
  ports:
    - protocol: TCP
      name: http
      port: 8585
      targetPort: 8585
      nodePort: 30000