apiVersion: v1
kind: Service
metadata:
  name: intellipaat-app-service
spec:
  type: NodePort
  selector:
    app: intellipaat-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8585
      nodePort: 30000
      type: NodePort
